M48
; DRILL file {KiCad (6.99.0-228-g2fdbc41b8f)} date Fri Jan 21 20:17:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-21T20:17:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-228-g2fdbc41b8f)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X4.9819Y-1.4976
X5.4465Y-1.4976
T0
M30
